import argparse
import glob
import logging
import os
from pathlib import Path

import numpy as np

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger(__name__)

def analyze_episode_topology(episode_dir: Path):
    report_path = episode_dir / "topology_analysis_report.md"
    
    step_dirs = sorted(glob.glob(str(episode_dir / "step_*")))
    
    if not step_dirs:
        log.error(f"No step directories found in {episode_dir}")
        return

    log.info(f"Analyzing {len(step_dirs)} steps in {episode_dir}")
    
    report_lines = [
        f"# SYNAPSE Topological Diagnostics Report",
        f"**Target Episode Directory:** `{episode_dir}`",
        f"**Number of Rollout Steps:** {len(step_dirs)}",
        "",
        "## Executive Summary",
        "This report tracks the stability and structure of the latent geometric invariants (Persistent Homology) generated by the SYNAPSE Topology Branch during an autoregressive rollout.",
        "",
        "## Step-by-Step Evolution",
        ""
    ]
    
    topo_norms = []
    anchor_counts = []
    y_star_means = []
    
    for step_dir_str in step_dirs:
        step_dir = Path(step_dir_str)
        step_name = step_dir.name
        npz_path = step_dir / "topology_data.npz"
        
        if not npz_path.exists():
            continue
            
        data = np.load(npz_path)
        point_cloud = data['point_cloud']
        anchor_indices = data['anchor_indices']
        y_star = data['y_star']
        topology_summary = data['topology_summary']
        
        # Analytics
        t_norm = np.linalg.norm(topology_summary)
        topo_norms.append(t_norm)
        
        num_anchors = len(anchor_indices)
        anchor_counts.append(num_anchors)
        
        y_mean = np.mean(y_star) if len(y_star) > 0 else 0
        y_star_means.append(y_mean)
        
        cloud_variance = np.var(point_cloud, axis=0).mean() if len(point_cloud) > 0 else 0
        
        report_lines.extend([
            f"### {step_name.upper()}",
            f"- **Anchor Count**: {num_anchors}",
            f"- **Y* (Saliency) Mean**: {y_mean:.4f}",
            f"- **Latent Cloud Variance**: {cloud_variance:.4f}",
            f"- **Topology Summary Norm**: {t_norm:.4f}",
            "",
            "#### Visualizations",
            "| PCA Projection | Persistence Diagram |",
            "|:---:|:---:|",
            f"| ![{step_name} PCA]({step_name}/point_cloud_pca.png) | ![{step_name} PD]({step_name}/persistence_diagram.png) |",
            ""
        ])
        
    # Quantitative Drift Analysis
    report_lines.extend([
        "## Drift Analysis",
        "During an autoregressive rollout, the model predictions form a closed loop. If the topology invariants fluctuate wildly, the model is reacting to noise and failing to abstract the geometry robustly. If they remain perfectly static despite action changes, the topology branch is suffering from representation collapse (ignoring the history).",
        ""
    ])
    
    if len(topo_norms) > 1:
        topo_drift = np.std(topo_norms) / np.mean(topo_norms) if np.mean(topo_norms) > 0 else 0
        report_lines.append(f"- **Topology Summary Coefficient of Variation (CV)**: {topo_drift:.4%}")
        
        if topo_drift < 0.01:
            report_lines.append("> ⚠️ **WARNING: Representation Collapse.** The topology vector is almost completely static over the rollout. The Transformer is likely ignoring the topological features because they contain no dynamic path information. This perfectly explains the performance regression compared to the A1 baseline.")
        elif topo_drift > 0.5:
            report_lines.append("> ⚠️ **WARNING: Topological Noise.** The topology summary is fluctuating wildly. The geometry is hypersensitive to the autoregressive predictions, causing a compounding error cascade.")
        else:
            report_lines.append("> ✅ **HEALTHY: Structured Variation.** The topology summary varies moderately across steps, suggesting it is dynamically tracking the unfolding trajectory.")
            
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("\n".join(report_lines))
        
    log.info(f"Successfully generated topology analysis report at: {report_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Analyze dumped topology data")
    parser.add_argument("--dir", type=str, required=True, help="Path to episode dump directory (e.g., topology_dumps/episode_0000)")
    args = parser.parse_args()
    
    episode_dir = Path(args.dir)
    if not episode_dir.exists():
        log.error(f"Directory {episode_dir} does not exist.")
    else:
        analyze_episode_topology(episode_dir)
