# FILE: scripts/bootstrap_training_data.py
# (Definitive, Robust SOTA Data Factory)

import argparse
import logging
import os
import shutil
import subprocess
import sys
import time
import yaml
from pathlib import Path

# Project imports for inline verification
# Ensure the project root is in path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

try:
    from SYNAPSIS.datasets.expert_dataset import ExpertTrajectoryDataset
except ImportError:
    ExpertTrajectoryDataset = None

# Configure UTF-8 for Windows CLI robustness
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')

# Configure Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | [BOOTSTRAP] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)
log = logging.getLogger("Bootstrap")

def run_command(cmd_list, cwd=None):
    """Runs a shell command with real-time logging, PYTHONPATH injection, and error checking."""
    cmd_str = " ".join([str(x) for x in cmd_list])
    log.info(f"EXEC: {cmd_str}")
    
    # Robust PYTHONPATH injection to ensure SYNAPSIS is found by subprocesses
    env = os.environ.copy()
    env["PYTHONPATH"] = str(ROOT) + os.pathsep + env.get("PYTHONPATH", "")
    
    try:
        # Run and stream output to stdout so the user sees progress bars
        subprocess.run(cmd_list, check=True, cwd=cwd, env=env)
    except subprocess.CalledProcessError as e:
        log.error(f"❌ Command failed with exit code {e.returncode}")
        log.error(f"Failed Command: {cmd_str}")
        sys.exit(1)

def robust_rmtree(path):
    """Robustly deletes a directory, handling Windows file locks."""
    if not path.exists(): return
    try:
        shutil.rmtree(path)
    except PermissionError:
        log.warning(f"Windows lock detected on {path}. Waiting to retry deletion...")
        time.sleep(2.0)
        try:
            shutil.rmtree(path)
        except Exception as e:
            log.error(f"Failed to delete {path}: {e}")

def main():
    parser = argparse.ArgumentParser(description="SOTA Data Factory")
    parser.add_argument("--episodes", type=int, default=None, help="Total episodes to generate (overrides config)")
    parser.add_argument("--workers", type=int, default=None, help="Number of parallel workers (overrides config)")
    parser.add_argument("--seed", type=int, default=None, help="Base seed (overrides config)")
    parser.add_argument("--output_dir", type=str, default=None, help="Base output directory (overrides config)")
    parser.add_argument("--config_template", type=str, default="SYNAPSIS/configs/dataset/generate.yaml", help="Base config to inherit")
    parser.add_argument("--keep-raw", action="store_true", help="If set, keeps the raw shards after processing")
    args = parser.parse_args()

    # --- 1. Load Config (Source of Truth) ---
    config_path = Path(args.config_template).resolve()
    if not config_path.exists():
        log.error(f"❌ Config template not found: {config_path}")
        sys.exit(1)
        
    with open(config_path, "r") as f:
        config_data = yaml.safe_load(f)

    # Sync arguments: CLI > Config > Script Defaults
    args.episodes = args.episodes or config_data.get("num_episodes", 20)
    args.workers = args.workers or config_data.get("num_workers", 2)
    args.seed = args.seed or config_data.get("seed", 12345)
    args.output_dir = args.output_dir or config_data.get("output_dir", "./output_data/bootstrap/")
    run_name = config_data.get("run_name", f"boot_{int(time.time())}")

    # --- 2. Setup Paths ---
    base_dir = Path(args.output_dir).resolve()
    raw_shards_dir = base_dir / "raw_shards"
    final_data_dir = base_dir / "final_training_set"
    
    # Predict the output path generated by generate_dataset.py
    # Logic: out_dir / {expert_{run_name}_{episodes}_episodes} / {same_name}.lmdb
    expected_dataset_folder_name = f"expert_{run_name}_{args.episodes}_episodes"
    raw_dataset_path = raw_shards_dir / expected_dataset_folder_name
    raw_lmdb_file = raw_dataset_path / f"{expected_dataset_folder_name}.lmdb"

    # Clean previous run if exists to prevent pollution
    if base_dir.exists():
        log.warning(f"Cleaning existing output directory: {base_dir}")
        shutil.rmtree(base_dir)
    
    base_dir.mkdir(parents=True, exist_ok=True)
    raw_shards_dir.mkdir(parents=True, exist_ok=True)
    final_data_dir.mkdir(parents=True, exist_ok=True)

    # --- 3. Determine Final Config for Generation ---
    # If no CLI overrides relevant to the generator were provided, use the original config directly
    is_dirty = (args.episodes != config_data.get("num_episodes") or 
                args.workers != config_data.get("num_workers") or 
                args.seed != config_data.get("seed") or
                str(raw_shards_dir).replace("\\","/") != str(config_data.get("output_dir")).replace("\\","/"))

    if not is_dirty:
        final_gen_config = config_path
        log.info(f"Using master config as source of truth: {final_gen_config}")
        temp_config_path = None
    else:
        log.info("--- Preparing Ephemeral Configuration (Overrides Detected) ---")
        temp_config_path = base_dir / f"temp_bootstrap_{run_name}.yaml"
        
        # Inject Overrides
        config_data["run_name"] = run_name
        config_data["num_episodes"] = args.episodes
        config_data["num_workers"] = args.workers
        config_data["seed"] = args.seed
        config_data["output_dir"] = str(raw_shards_dir)
        
        with open(temp_config_path, "w") as f:
            yaml.dump(config_data, f)
        
        final_gen_config = temp_config_path
        log.info(f"Temporary config written to: {temp_config_path}")

    try:
        # --- 4. Step 1: Generation ---
        log.info(">>> STEP 1: Generating Raw Trajectories...")
        
        gen_cmd = [
            sys.executable, str(ROOT / "scripts" / "generate_dataset.py"),
            "--config", str(final_gen_config),
        ]
        run_command(gen_cmd, cwd=str(ROOT))

        # Validate Generation
        if not raw_lmdb_file.exists():
            log.error(f"❌ Generation Failed. Expected LMDB file not found at: {raw_lmdb_file}")
            log.error(f"Contents of shard dir: {list(raw_shards_dir.glob('*'))}")
            sys.exit(1)
        
        log.info(f"✅ Raw Data generated successfully at: {raw_lmdb_file}")



        log.info(">>> STEP 2: Calculating Advantages & Injecting Weights...")
        
        # The destination file name
        final_lmdb_path = final_data_dir / "training_set.lmdb"
        
        adv_cmd = [
            sys.executable, "-m", "SYNAPSIS.utils.advantage_calculator",
            "--source-db", str(raw_lmdb_file),
            "--dest-db", str(final_lmdb_path),
            "--gamma", "0.99",
            "--overwrite"
        ]
        run_command(adv_cmd, cwd=str(ROOT))

        if not final_lmdb_path.exists():
            log.error("❌ Advantage calculation failed. Output file missing.")
            sys.exit(1)

        log.info(f"✅ Advantages injected. Final dataset at: {final_lmdb_path}")
        if not args.keep_raw:
            log.info(">>> CLEANUP: Deleting raw shards to save space...")
            # Ensure we release any file handles first (Advantage Calculator should have closed them)
            time.sleep(1.0) 
            robust_rmtree(raw_shards_dir)
            log.info("✅ Raw shards deleted.")
        else:
            log.info("ℹ️ Keeping raw shards (--keep-raw set).")
        # --- 5. Step 3: Integrity Check (Smoke Test) ---
        log.info(">>> STEP 3: Verifying Data Integrity (Smoke Test)...")
        
        if ExpertTrajectoryDataset is None:
            log.warning("⚠️ utils.expert_dataset not importable. Skipping inline Python check.")
        else:
            try:
                # Attempt to open the dataset and read the last sample
                # We use minimal horizons just to check file structure/index
                ds = ExpertTrajectoryDataset(
                    demo_path=str(final_lmdb_path),
                    observation_horizon=1,
                    action_horizon=1
                )
                num_eps = ds.get_num_episodes()
                
                if num_eps != args.episodes:
                    log.error(f"❌ Episode Count Mismatch! Expected {args.episodes}, found {num_eps}")
                    sys.exit(1)
                
                # Try reading one sample from the middle
                sample = ds[len(ds) // 2]
                if sample is None:
                    raise ValueError("Sample returned None")
                
                log.info(f"✅ Integrity Verified. Dataset contains {num_eps} episodes and is readable.")
                del ds # Close handle
                
            except Exception as e:
                log.error(f"❌ Data Integrity Check Failed: {e}")
                sys.exit(1)

        # --- 4. Step 2: Advantage Calculation ---
        # Success Summary
        log.info("\n" + "="*60)
        log.info(f"🚀 BOOTSTRAP COMPLETE")
        log.info(f"📂 Final Dataset: {final_lmdb_path}")
        log.info(f"📊 Episodes: {args.episodes}")
        log.info("="*60 + "\n")

    finally:
        # Cleanup
        if temp_config_path and temp_config_path.exists():
            log.info("Cleaning up temporary config...")
            temp_config_path.unlink()

if __name__ == "__main__":
    main()